// lib/exportMarkdown.ts
// ──────────────────────────────────────────────
// Generates a Markdown document from the analysis
// ──────────────────────────────────────────────

interface Step {
  id: number;
  actor: string;
  action: string;
  system?: string;
  type: string;
  isBottleneck?: boolean;
  bottleneckReason?: string;
}

interface Bottleneck {
  stepId: number;
  title: string;
  severity: string;
  description: string;
  risk?: string;
  recommendation?: string;
}

interface Improvement {
  title: string;
  description: string;
  impact: string;
  estimatedGain?: string;
  leanPrinciple?: string;
  enabler?: string;
}

interface Metrics {
  totalSteps: number;
  manualSteps: number;
  automatedSteps: number;
  decisionPoints: number;
  handoffs: number;
  bottleneckCount: number;
  automationPercentage: number;
  processHealthScore: number;
}

interface AnalysisResult {
  summary: string;
  steps: Step[];
  mermaidCode: string;
  bottlenecks: Bottleneck[];
  improvements: Improvement[];
  metrics: Metrics;
}

export function generateMarkdown(analysis: AnalysisResult, processDescription?: string): string {
  const now = new Date().toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  let md = "";

  // ─── Title ─────────────────────────────
  md += `# Process Analysis Report\n`;
  md += `**Generated:** ${now}\n`;
  md += `**Tool:** Process Documentation Agent (Claude AI)\n\n`;
  md += `---\n\n`;

  // ─── Executive Summary ─────────────────
  md += `## Executive Summary\n\n`;
  md += `${analysis.summary}\n\n`;

  // ─── Process Description ───────────────
  if (processDescription) {
    md += `## Original Process Description\n\n`;
    md += `> ${processDescription.replace(/\n/g, "\n> ")}\n\n`;
  }

  // ─── Metrics ───────────────────────────
  md += `## Process Metrics\n\n`;
  md += `| Metric | Value |\n`;
  md += `|--------|-------|\n`;
  md += `| Total Steps | ${analysis.metrics.totalSteps} |\n`;
  md += `| Manual Steps | ${analysis.metrics.manualSteps} |\n`;
  md += `| Automated Steps | ${analysis.metrics.automatedSteps} |\n`;
  md += `| Decision Points | ${analysis.metrics.decisionPoints} |\n`;
  md += `| Handoffs | ${analysis.metrics.handoffs} |\n`;
  md += `| Bottlenecks | ${analysis.metrics.bottleneckCount} |\n`;
  md += `| Automation Rate | ${analysis.metrics.automationPercentage}% |\n`;
  md += `| Process Health Score | ${analysis.metrics.processHealthScore}/100 |\n\n`;

  // ─── Flowchart ─────────────────────────
  if (analysis.mermaidCode) {
    md += `## Process Flowchart\n\n`;
    md += `\`\`\`mermaid\n`;
    md += `${analysis.mermaidCode.replace(/\\n/g, "\n").replace(/\\"/g, '"')}\n`;
    md += `\`\`\`\n\n`;
  }

  // ─── Process Steps ─────────────────────
  if (analysis.steps && analysis.steps.length > 0) {
    md += `## Process Steps\n\n`;
    md += `| # | Actor | Action | System | Type | Bottleneck |\n`;
    md += `|---|-------|--------|--------|------|------------|\n`;
    analysis.steps.forEach((step) => {
      const bottleneck = step.isBottleneck ? `Yes — ${step.bottleneckReason || ""}` : "No";
      md += `| ${step.id} | ${step.actor} | ${step.action} | ${step.system || "—"} | ${step.type} | ${bottleneck} |\n`;
    });
    md += `\n`;
  }

  // ─── Bottlenecks ───────────────────────
  if (analysis.bottlenecks && analysis.bottlenecks.length > 0) {
    md += `## Bottlenecks Identified\n\n`;
    analysis.bottlenecks.forEach((b, i) => {
      md += `### ${i + 1}. ${b.title} (${b.severity})\n\n`;
      md += `${b.description}\n\n`;
      if (b.risk) md += `**Risk:** ${b.risk}\n\n`;
      if (b.recommendation) md += `**Recommendation:** ${b.recommendation}\n\n`;
    });
  }

  // ─── Improvements ─────────────────────
  if (analysis.improvements && analysis.improvements.length > 0) {
    md += `## Recommended Improvements\n\n`;
    analysis.improvements.forEach((imp, i) => {
      md += `### ${i + 1}. ${imp.title} (${imp.impact} Impact)\n\n`;
      md += `${imp.description}\n\n`;
      if (imp.estimatedGain) md += `**Estimated Gain:** ${imp.estimatedGain}\n\n`;
      if (imp.leanPrinciple) md += `**Lean Principle:** ${imp.leanPrinciple}\n\n`;
      if (imp.enabler) md += `**Enabler:** ${imp.enabler}\n\n`;
    });
  }

  // ─── Footer ────────────────────────────
  md += `---\n\n`;
  md += `*Generated by Process Documentation Agent — powered by Claude AI, Next.js, and Mermaid.js*\n`;

  return md;
}

export function downloadMarkdown(markdown: string, filename?: string) {
  const blob = new Blob([markdown], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename || `process-analysis-${Date.now()}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}